services:
  localstack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb
    volumes:
      - ./init.sh:/etc/localstack/init/ready.d/init.sh
