services:
  localstack:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3,dynamodb,iam,lambda
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./init.sh:/etc/localstack/init/ready.d/init.sh
