services:
  dev: &base
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    volumes:
      - .:/project
      - /project/node_modules
    environment:
      - API_HOST=http://localhost:8000
    ports:
      - 3000:3000
    command: dev

  build:
    <<: *base
    build:
      args:
        - NODE_ENV=production
    ports: []
    command: build
