name: Build and push api

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
      ecr-repository:
        type: string
        required: true
      assume-role-arn:
        type: string
        required: true

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    name: Build and push api
    runs-on: ubuntu-24.04  # linux/amd64
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build api
        run: |
          docker build -f ./Dockerfile \
            -t ${{ inputs.ecr-repository }}:${IMAGE_TAG} \
            -t ${{ inputs.ecr-repository }}:latest \
            .

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ inputs.assume-role-arn }}
          role-session-name: github-actions-api

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Push image to Amazon ECR
        run: docker push -a ${{ inputs.ecr-repository }}
