name: cd_admin

on:
  workflow_call:
    inputs:
      role-to-assume:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1

      - name: Log in to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/admin/Dockerfile
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/admin:${{ github.sha }}
            ${{ steps.login-ecr.outputs.registry }}/admin:latest
          push: true
