name: cd_lambda

on:
  workflow_call:
    inputs:
      role-to-assume:
        required: true
        type: string
      function-name:
        required: true
        type: string
      tfstate-bucket:
        required: true
        type: string
      photos-target-bucket:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: lambda

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Zip function
        run: |
          docker compose build zip
          docker compose run zip
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: lambda/output/function.zip

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: lambda/functions/${{ inputs.function-name }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: lambda/functions/${{ inputs.function-name }}

      - name: Setup lambroll
        uses: fujiwara/lambroll@v1
        with:
          version: v1.3.2

      - name: Deploy
        run: TARGET_BUCKET=${{ inputs.photos-target-bucket }} lambroll --tfstate=s3://${{ inputs.tfstate-bucket }}/apkas.tfstate --function=function.jsonnet deploy --src function.zip
