name: Build and sync frontend

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
      api-host:
        type: string
        required: true
      assume-role-arn:
        type: string
        required: true
      s3-bucket:
        type: string
        required: true
      distribution-id:
        type: string
        required: true

jobs:
  build_and_sync:
    name: Build and sync frontend
    runs-on: ubuntu-24.04-arm
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build frontend
        run: docker compose run -e API_HOST=${{ inputs.api-host }} build

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: ${{ inputs.assume-role-arn }}
          role-session-name: github-actions

      - name: Sync output to S3
        run: aws s3 sync ./out s3://${{ inputs.s3-bucket }} --delete --exact-timestamps

      - name: Purge cache
        run: aws cloudfront create-invalidation --distribution-id ${{ inputs.distribution-id }} --paths "/*"
