name: Deploy frontend

on:
  workflow_call:
    inputs:
      role-to-assume:
        required: true
        type: string
      s3-bucket-name:
        required: true
        type: string
      cloudfront-distribution-id:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: frontend/.bun-version

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.role-to-assume }}
          aws-region: ap-northeast-1

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist

      - name: Sync S3
        run: aws s3 sync ./dist s3://${{ inputs.s3-bucket-name }} --delete --exact-timestamp

      - name: Purge cache
        run: aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront-distribution-id }} --paths "/*"
