name: Test public

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: apps/public

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: apps/public/.bun-version

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint

  unit-test:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup localstack
        run: docker compose up -d
        working-directory: localstack

      - name: Wait for localstack to ready
        run: ./.github/scripts/wait_localstack.sh

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: apps/public/.bun-version

      - name: Install dependencies
        run: bun install
        working-directory: apps/public

      - name: Run unit test
        run: bun test
        working-directory: apps/public
