name: CD for frontend

on:
  push:
    branches:
      - main
      - feature/deploy_to_staging  # 動作確認用

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::183295408601:role/github-actions
          aws-region: ap-northeast-1

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: frontend/.bun-version

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-24.04

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::183295408601:role/github-actions
          aws-region: ap-northeast-1

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist

      - name: Sync S3
        run: aws s3 sync ./dist s3://apkas-staging-frontend --delete --exact-timestamp
