name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      root: ${{ steps.filter.outputs.root }}
      diary: ${{ steps.filter.outputs.diary }}
      public: ${{ steps.filter.outputs.public }}
      admin: ${{ steps.filter.outputs.admin }}
      lambda: ${{ steps.filter.outputs.lambda }}

    steps:
      - uses: actions/checkout@v5

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        id: filter
        with:
          filters: |
            root:
              - '.github/workflows/ci.yml'
              - '*bun*'
              - '.dockerignore'
              - '*.mjs'
              - '*.json'
            diary:
              - '.github/workflows/*diary*.yml'
              - 'packages/diary/**'
            public:
              - '.github/workflows/*public*.yml'
              - 'apps/public/**'
            admin:
              - '.github/workflows/*admin*.yml'
              - 'apps/admin/**'
            lambda:
              - '.github/workflows/ci.yml'
              - '.github/workflows/*lambda*.yml'
              - 'lambda/**'

  diary:
    needs: changes
    if: ${{ needs.changes.outputs.root == 'true' || needs.changes.outputs.diary == 'true' }}
    uses: ./.github/workflows/_ci_diary.yml

  public:
    needs: changes
    if: ${{ needs.changes.outputs.root == 'true' || needs.changes.outputs.public == 'true' }}
    uses: ./.github/workflows/_ci_public.yml

  admin:
    needs: changes
    if: ${{ needs.changes.outputs.root == 'true' || needs.changes.outputs.admin == 'true' }}
    uses: ./.github/workflows/_ci_admin.yml

  lambda:
    needs: changes
    if: ${{ needs.changes.outputs.lambda == 'true' }}
    uses: ./.github/workflows/_ci_lambda.yml
