name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  diary:
    uses: ./.github/workflows/_ci_diary.yml

  public:
    uses: ./.github/workflows/_ci_public.yml

  admin:
    uses: ./.github/workflows/_ci_admin.yml