name: CI for api

on:
  pull_request:
    paths:
      - ".github/workflows/ci_api.yml"
      - "api/**"

jobs:
  lint_and_format:
    uses: ./.github/workflows/_lint_and_format_api.yml
    with:
      working-directory: api
      uv-version: "0.25.5"

  typecheck_and_test:
    uses: ./.github/workflows/_typecheck_and_test_api.yml
    with:
      working-directory: api
      uv-version: "0.25.5"
