name: CI for api

on:
  pull_request:
    paths:
      - ".github/workflows/*api*.yml"
      - "api/**"

jobs:
  test:
    uses: ./.github/workflows/_test_api.yml
    with:
      working-directory: api
