name: CI for frontend

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: frontend/.bun-version

      - name: Install dependencies
        run: bun install

      - name: Run lint
        run: bun lint
