name: cicd_lambda

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*lambda*.yml'
      - 'lambda/**'
      - '!**/*.md'

permissions:
  contents: read
  id-token: write

jobs:
  ci_lambda:
    uses: ./.github/workflows/_ci_lambda.yml

  # cd:
  #   needs: [ci_lambda]
