name: CI/CD for api

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/*api*.yml"
      - "api/**"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_test_api.yml
    with:
      working-directory: api

  deploy:
    needs: [test]
    uses: ./.github/workflows/_deploy_api.yml
    with:
      working-directory: api
      app-env: staging
      ecr-repository: 183295408601.dkr.ecr.ap-northeast-1.amazonaws.com/api
      assume-role-arn: arn:aws:iam::183295408601:role/github-actions
