name: CI/CD for frontend

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/*frontend*.yml"
      - "frontend/**"
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/_test_frontend.yml
    with:
      working-directory: frontend

  deploy:
    needs: [test]
    uses: ./.github/workflows/_deploy_frontend.yml
    with:
      working-directory: frontend
      api-host: https://api.dev.apkas.net
      assume-role-arn: arn:aws:iam::183295408601:role/github-actions
      s3-bucket: apkas-staging-frontend
      distribution-id: E2B0AWVJTLM7IR
