name: Release api

on:
  push:
    tags: ["v*"]

jobs:
  test:
    uses: ./.github/workflows/_test_api.yml
    with:
      working-directory: api

  deploy:
    needs: [test]
    uses: ./.github/workflows/_deploy_api.yml
    with:
      working-directory: api
      app-env: production
      ecr-repository: 961341543806.dkr.ecr.ap-northeast-1.amazonaws.com/api
      assume-role-arn: arn:aws:iam::961341543806:role/github-actions
